language: cpp

before_install:
  - chmod +x install-dependencies.sh
  - ./install-dependencies.sh

script:
  - cd Tests
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ./tests
