language: cpp

before_install:
  - chmod +x scripts/install-dependencies.sh
  - ./scripts/install-dependencies.sh

script:
  - chmod +x scripts/build-stocksnews.sh
  - ./scripts/build-stocksnews.sh
  - chmod +x scripts/test-units.sh
  - ./scripts/test-units.sh
  - chmod +x scripts/test-stocksnews.sh
  - ./scripts/test-stocksnews.sh

#deploy:
#  - provider: codedeploy
#    access_key_id: ""
#    secret_access_key: ""
#    bucket: "S3 Bucket"
#    key: latest/MyApp.zip
#    application: StocksNews
#    deployment_group: StocksNews
#    region: eu-west-3c
