language: cpp

before_install:
  - chmod +x scripts/install-dependencies.sh
  - ./scripts/install-dependencies.sh

script:
  - chmod +x scripts/build-stocksnews.sh
  - ./scripts/build-stocksnews.sh
  - chmod +x scripts/test-units.sh
  - ./scripts/test-units.sh

after_success:
  - cd /home/travis/build/lulu731/StocksNews/build
  - ./stocksnews
  - cd ~
  - pwd

