matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

language: cpp

before_install:
  - sudo apt-get update -qq 
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y libboost-all-dev   


script:
  - ls /usr/lib/* 
  - cd Tests
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ./tests

