#matrix:
#  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

language: cpp

before_install:
  - cd ..
  - mkdir boost
  - cd boost
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
  - tar --bzip2 -xf boost_1_67_0.tar.bz2
  - cd boost_1_67_0
  - ./bootstrap.sh --prefix=../installation --with-libraries=test,system,filesystem
  - ./b2 -d0 install
  - cd ..
  - cd ..

script: 
  - cd StocksNews
  - cd Tests
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ./tests
