before_install :
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev

language : cpp

script:
  - cd Tests
  - mkdir build
  - mkdir stocks
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ./tests

